{% set name = "xinvert" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 594ab01c2f9227589fe26539d13ca3fd8dfc1bc709093c0275d7f64512d2ab85

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - xarray
    - dask
    - numpy
    - numba
    - netCDF4
    - scipy

test:
  imports:
    - xinvert
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/miniufo/xinvert
  summary: 'Invert geophysical fluid dynamic problems (elliptic partial differential equations) using SOR iteration method'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://xinvert.readthedocs.io/
  dev_url: https://github.com/miniufo/xinvert

extra:
  recipe-maintainers:
    - miniufo
